name: flutter_uploadcare
description: Flutter integration for uploadcare.
version: 1.0.0
homepage: https://github.com/amondnet/uploadcare.dart.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  freezed_annotation: ^0.14.2
  uploadcare: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^2.0.4
  freezed: ^0.14.2
  mocktail: ^0.1.2


