name: flutter_uploadcare
description: Flutter integration for uploadcare.
version: 0.1.0+1
homepage: https://github.com/amondnet/uploadcare.dart.git

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  freezed_annotation: ">0.7.1 <1.0.0"
  uploadcare: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.14.3
  build_runner: ^1.10.0
  freezed: ^0.11.5
  mockito: ^4.1.1


