name: uploadcare_flutter
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.7.1


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
  build_runner: ^1.10.0
  freezed: ^0.10.8

