name: uploadcare
description: Dart library for Uploadcare.
version: 1.0.0
homepage: https://github.com/amondnet/uploadcare.dart.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.2
  crypto: ^3.0.1
  intl: ^0.17.0
  http: ^0.13.3
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  http2: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.2

  mockito: ^5.0.8
  test_cov: ^1.0.1
  remove_from_coverage: ^2.0.0

