name: uploadcare
description: Dart library for Uploadcare.
version: 0.2.0
homepage: https://github.com/amondnet/uploadcare.dart.git

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.7.1
  crypto: ^2.1.4
  intl: ^0.16.1
  http: ^0.12.1
  restio: ^0.10.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
  build_runner: ^1.10.0
  freezed: ^0.10.8
  json_serializable: ^3.3.0

  mockito: ^4.1.1
  test_coverage: ^0.4.1
  remove_from_coverage: ^1.0.7

