name: uploadcare
description: Dart library for Uploadcare.
version: 1.2.0
homepage: https://github.com/amondnet/uploadcare.dart.git

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  freezed_annotation: '>=2.0.0 <3.0.0'
  crypto: ^3.0.1
  intl: '>=0.17.0 <1.0.0'
  http: ^0.13.3
  http2: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.4
  build_runner: ^2.0.4
  freezed: ^2.3.3
  json_serializable: ^6.6.2

  mockito: ^5.0.8
  test_cov: ^1.0.1
  remove_from_coverage: ^2.0.0

