name: Build

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    container:
      image: google/dart:${{ matrix.version }}

    strategy:
      matrix:
        package: ["uploadcare"]
        version: ["latest", "dev"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: pub get

      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: |
          pub test
          pub run test_coverage --badge false
          pub run remove_from_coverage -f coverage/lcov.info -r '.freezed.dart$'

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info